version: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
     
      - ./src/app:/app
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mysql
      - postgres
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: desafio_dp
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: desafio_dp
      PYTHONPATH: /app

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: desafio_dp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: desafio_dp
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data: